export default function PcBuildsData() {
  return [
    {
      title: 'ASUS ROG Galore',
      performance: 10,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'Republic of Gamers',
      image: '../images/phanteksevolvxbk.jpg',
      keyFacts:
        'If you are a fan of ASUS Republic of Gamers ecosystem, then this is the right build for you. Price-Performance ratio aside, you get all the bells and whistles and nearly unbeatable performance.',
      parts: [
        {
          partManufacturer: 'Intel',
          partName: 'i9-9900K',
          partPrice: 527.99,
          partUrl: 'https://amzn.to/2TmvO1X',
          partAsin: 'asin.B005404P9I',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG STRIX GEFORCE RTX2080TI',
          partPrice: 1399,
          partUrl: 'https://amzn.to/2Tj4KAv',
          partAsin: 'asin.B07K4B9T6M',
        },
        {
          partManufacturer: 'Phanteks',
          partName: 'Enthoo Evolv X Black',
          partPrice: 212.99,
          partUrl: 'https://amzn.to/2Jpy4W8',
          partAsin: 'asin.B07GY26TZJ',
        },
        {
          partManufacturer: 'G.Skill',
          partName: 'Trident Z RGB 32 GB DDR4 3200 (8GBx4)',
          partPrice: 362.34,
          partUrl: 'https://amzn.to/2TZdU9A',
          partAsin: 'asin.B01MSBS0UT',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Maximus XI Formula',
          partPrice: 470.99,
          partUrl: 'https://amzn.to/2Jqwfse',
          partAsin: 'asin.B07J54MQ5X',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Ryujin 360',
          partPrice: 249.99,
          partUrl: 'https://amzn.to/2WdNxKK',
          partAsin: 'asin.B07JVQXH8M',
        },
        {
          partManufacturer: 'Samsung',
          partName: '970 Evo Plus 1TB',
          partPrice: 226.18,
          partUrl: 'https://amzn.to/2Hvqnw6',
          partAsin: 'asin.B07MBQPQ62',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Thor-850P',
          partPrice: 239.99,
          partUrl: 'https://amzn.to/2HxQsub',
          partAsin: 'asin.B07HZ9JKN7',
        },
        {
          partManufacturer: 'CableMod',
          partName: 'PRO ModMesh RT-Series ASUS ROG/Seasonic',
          partPrice: 104.9,
          partUrl: 'https://amzn.to/2WisYgh',
          partAsin: 'asin.B07JL2KSGX',
        },
      ],
    },
    {
      title: 'Awesome Gaming Build',
      performance: 7,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'Long time daily driver',
      image: '../images/phanteksp300tgbk.jpg',
      keyFacts:
        'A build capable of all modern titles up to WQHD-resolution and simultanous streaming. A great choice for ambitious gamers without spending a fortune. Maybe a perfect start for your streaming career?',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'Phanteks',
          partName: 'Eclipse P300 Tempered Glass',
          partPrice: 62.94,
          partUrl: 'https://amzn.to/2Cgb4TO',
          partAsin: 'asin.B075DMYVBV',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 16GB BLS2K8G4D30BESBK (8GB x2)',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },

    {
      title: 'Great Workstation build',
      performance: 8.5,
      bookmarked: false,
      category: 'editing',
      subtitle: 'Edit like a Pro!',
      image: '../images/fractaldesignmeshifyctg.jpg',
      keyFacts:
        'You are content creator or need a PC for streaming? Then maybe this is the build for you. At this price point and with minimal overclocking effort the AMD Ryzen 7 2700 is the best CPU choice for decent workstations and does not have to hide.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 7 2700',
          partPrice: 219.9,
          partUrl: 'https://amzn.to/2JNjxDQ',
          partAsin: 'asin.B07B41717Z',
        },
        {
          partManufacturer: 'KFA2',
          partName: 'GeForce RTX 2070 EX 8GB',
          partPrice: 499.0,
          partUrl: 'https://amzn.to/2U0kihF',
          partAsin: 'asin.B07L2RHJS7',
        },
        {
          partManufacturer: 'Fractal Design',
          partName: 'Meshify C Tempered Glass',
          partPrice: 92.58,
          partUrl: 'https://amzn.to/2Tx4Edz',
          partAsin: 'asin.B079FQZM89',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT BLS4C8G4D240FSB 32GB (8GBx4)',
          partPrice: 226.36,
          partUrl: 'https://amzn.to/2OsTyRa',
          partAsin: 'asin.B00UFBZOLE',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'be quiet!',
          partName: 'Dark Rock 4',
          partPrice: 58.85,
          partUrl: 'https://amzn.to/2Yjg0Rf',
          partAsin: 'asin.B07BYP9S95',
        },
        {
          partManufacturer: 'Samsung',
          partName: 'SSD 970 EVO Plus 500 GB M.2',
          partPrice: 123.99,
          partUrl: 'https://amzn.to/2WoMmIs',
          partAsin: 'asin.B07MFBLN7K',
        },
        {
          partManufacturer: 'WD',
          partName: 'Desktop Black 4 TB',
          partPrice: 185.99,
          partUrl: 'https://amzn.to/2TV1vo8',
          partAsin: 'asin.B0792G331G',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },

    {
      title: 'Step up your Office game',
      performance: 2,
      bookmarked: false,
      category: 'office',
      subtitle: 'Bargain Build',
      image: '../images/CoolerMasterMasterBoxE300L.jpg',
      keyFacts:
        'A fast, economical PC with Quad-Core CPU, SSD storage in a lightweight 300€ package. Works well for your daily Office and/or your Multimedia needs. This build is easily upgradable if more performance is needed.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 3 1200',
          partPrice: 72.89,
          partUrl: 'https://amzn.to/2UdCeEM',
          partAsin: 'asin.B0741DN383',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Master Box E300L',
          partPrice: 34.99,
          partUrl: 'https://amzn.to/2TyB3QR',
          partAsin: 'asin.B07C2KNP2Q',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Vengeance LPX 8GB (2x4GB)',
          partPrice: 57.9,
          partUrl: 'https://amzn.to/2OoY3fj',
          partAsin: 'asin.B0123ZB70Q',
        },
        {
          partManufacturer: 'Gigabyte',
          partName: 'B450M S2H',
          partPrice: 65.06,
          partUrl: 'https://amzn.to/2U8DVmV',
          partAsin: 'asin.B07KX428VH',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 240GB',
          partPrice: 35.99,
          partUrl: 'https://amzn.to/2Oomqty',
          partAsin: 'asin.B01F9G43WU',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'VS350',
          partPrice: 34.99,
          partUrl: 'https://amzn.to/2U2Maly',
          partAsin: 'asin.B00LMBQD3O',
        },
      ],
    },

    {
      title: 'Excellent Gaming build',
      performance: 8.5,
      bookmarked: false,
      category: 'gaming',
      subtitle: '4K, VR, np',
      image: '../images/lianlipco11dxbk.jpg',
      keyFacts:
        'High end build in a stylish tempered glass case, capable of 4K gaming in High to Ultra settings in most modern titles combined with a lightning fast NVME SSD and fancy RGB fans.',
      parts: [
        {
          partManufacturer: 'Intel',
          partName: 'Core i5-9600K',
          partPrice: 269.9,
          partUrl: 'https://amzn.to/2WoHAdT',
          partAsin: 'asin.B07HHLX1R8',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG STRIX GEFORCE RTX2070-A8G',
          partPrice: 579.0,
          partUrl: 'https://amzn.to/2WpoZOV',
          partAsin: 'asin.B07JBGY8JC',
        },
        {
          partManufacturer: 'Lian Li',
          partName: 'PC-O11DX Dynamic',
          partPrice: 130.06,
          partUrl: 'https://amzn.to/2HC2mCB',
          partAsin: 'asin.B07C88X1VV',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Vengeance RGB PRO 16GB (2x8GB) DDR4 3200MHz',
          partPrice: 137.91,
          partUrl: 'https://amzn.to/2YoZiQc',
          partAsin: 'asin.B07D1XCKWW',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Strix Z390-E',
          partPrice: 239.0,
          partUrl: 'https://amzn.to/2Wm7IpN',
          partAsin: 'asin.B07HS7C63T',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Hydro Series H150i PRO RGB',
          partPrice: 158.99,
          partUrl: 'https://amzn.to/2WkmltG',
          partAsin: 'asin.B077FZPCRH',
        },
        {
          partManufacturer: 'Samsung',
          partName: 'SSD 970 EVO Plus 1 TB M.2',
          partPrice: 224.9,
          partUrl: 'https://amzn.to/2OpHOyJ',
          partAsin: 'asin.B07MBQPQ62',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'LL120 RGB LED PWM 3 Fan Pack',
          partPrice: 92.9,
          partUrl: 'https://amzn.to/2HDNyEt',
          partAsin: 'asin.B075VGN4M1',
        },
      ],
    },

    {
      title: 'Budget Gaming Build',
      performance: 4.0,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'ideal for your esport needs',
      image: '../images/coolermasterq300l.jpg',
      keyFacts:
        'A great, cost effective gaming build for fluid gaming in FULL HD resolution and even capable as an entry level VR machine. You may want to overclock the CPU slightly to unleash the full potential of this decent Quad-Core.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 3 1200',
          partPrice: 72.89,
          partUrl: 'https://amzn.to/2UdCeEM',
          partAsin: 'asin.B0741DN383',
        },
        {
          partManufacturer: 'Sapphire',
          partName: 'RADEON RX 570 4GB NITRO+',
          partPrice: 144.9,
          partUrl: 'https://amzn.to/2OsrI7f',
          partAsin: 'asin.B079FX54KZ',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'MasterBox Q300L',
          partPrice: 49.93,
          partUrl: 'https://amzn.to/2Fcc9wh',
          partAsin: 'asin.B0785GRMPG',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 16GB BLS2K8G4D30BESBK (8GB x2)',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'Gigabyte',
          partName: 'B450M S2H',
          partPrice: 65.06,
          partUrl: 'https://amzn.to/2U8DVmV',
          partAsin: 'asin.B07KX428VH',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 500 GB',
          partPrice: 55.0,
          partUrl: 'https://amzn.to/2CCdOuA',
          partAsin: 'asin.B01F9G46Q8',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'MasterWatt 450 W',
          partPrice: 49.47,
          partUrl: 'https://amzn.to/2YqVjmv',
          partAsin: 'asin.B076PBT7H6',
        },
      ],
    },
    {
      title: 'NZXT Workstation Build',
      performance: 8.5,
      bookmarked: false,
      category: 'editing',
      subtitle: 'H700i Placeholder',
      image: '../images/nzxth700iw.jpg',
      keyFacts:
        'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'NZXT',
          partName: 'H700i White',
          partPrice: 199.9,
          partUrl: 'https://amzn.to/2Te0stY',
          partAsin: 'asin.B076JG8Z6N',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 16GB BLS2K8G4D30BESBK (8GB x2)',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },
    {
      title: 'Cooler Master SL600M',
      performance: 10,
      bookmarked: false,
      category: 'editing',
      subtitle: 'Cooler Master',
      image: '../images/coolermastersl600m.jpg',
      keyFacts:
        'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. test test test test',
      parts: [
        {
          partManufacturer: 'Intel',
          partName: 'i9-9900K',
          partPrice: 527.99,
          partUrl: 'https://amzn.to/2TmvO1X',
          partAsin: 'asin.B005404P9I',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG STRIX GEFORCE RTX2080TI',
          partPrice: 1399,
          partUrl: 'https://amzn.to/2Tj4KAv',
          partAsin: 'asin.B07K4B9T6M',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'MasterCase SL600M',
          partPrice: 167.99,
          partUrl: 'https://amzn.to/2JAaSEV',
          partAsin: 'asin.B07JQJBV33',
        },
        {
          partManufacturer: 'G.Skill',
          partName: 'Trident Z RGB 32 GB DDR4 3200 (8GBx4)',
          partPrice: 362.34,
          partUrl: 'https://amzn.to/2TZdU9A',
          partAsin: 'asin.B01MSBS0UT',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Maximus XI Formula',
          partPrice: 470.99,
          partUrl: 'https://amzn.to/2Jqwfse',
          partAsin: 'asin.B07J54MQ5X',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Ryujin 360',
          partPrice: 249.99,
          partUrl: 'https://amzn.to/2WdNxKK',
          partAsin: 'asin.B07JVQXH8M',
        },
        {
          partManufacturer: 'Samsung',
          partName: '970 Evo Plus 1TB',
          partPrice: 226.18,
          partUrl: 'https://amzn.to/2Hvqnw6',
          partAsin: 'asin.B07MBQPQ62',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Thor-850P',
          partPrice: 239.99,
          partUrl: 'https://amzn.to/2HxQsub',
          partAsin: 'asin.B07HZ9JKN7',
        },
        {
          partManufacturer: 'CableMod',
          partName: 'PRO ModMesh RT-Series ASUS ROG/Seasonic',
          partPrice: 104.9,
          partUrl: 'https://amzn.to/2WisYgh',
          partAsin: 'asin.B07JL2KSGX',
        },
      ],
    },
    {
      title: 'Fractal Design Define S2',
      performance: 8.5,
      bookmarked: false,
      category: 'editing',
      subtitle: 'Define S2 Placeholder',
      image: '../images/fractaldesigndefines2.jpg',
      keyFacts:
        'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'Radeon VII 16GB',
          partPrice: 799.0,
          partUrl: 'https://amzn.to/2OopiGR',
          partAsin: 'asin.B07NLVVL9D',
        },
        {
          partManufacturer: 'Fractal Design',
          partName: 'Define S2 Blackout',
          partPrice: 150.89,
          partUrl: 'https://amzn.to/2JC0U64',
          partAsin: 'asin.B07J1RMZB9',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 16GB BLS2K8G4D30BESBK (8GB x2)',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },
    {
      title: 'B/W Mini Placeholder',
      performance: 7.5,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'H200',
      image: '../images/nzxth200bw.jpg',
      keyFacts:
        'A build capable of all modern titles up to WQHD-resolution and simultanous streaming.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'NZXT',
          partName: 'H200B-W',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2U5XAUO',
          partAsin: 'asin.B07D7M8XR9',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 16GB BLS2K8G4D30BESBK (8GB x2)',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },
  ]
}
