export default function PcBuildsData() {
  return [
    {
      title: 'ASUS ROG Galore',
      performance: 10,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'Featured Build',
      image: '../images/phanteksevolvxbk.jpg',
      keyFacts:
        'ROG Lorem ipsum dolor sit amet, ROG consetetur sadipscing elitr ROG Lorem ipsum dolor sit amet, ROG consetetur sadipscing elitr ROG',
      parts: [
        {
          partManufacturer: 'Intel',
          partName: 'i9-9900K',
          partPrice: 527.99,
          partUrl: 'https://amzn.to/2TmvO1X',
          partAsin: 'asin.B005404P9I',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG STRIX GEFORCE RTX2080TI',
          partPrice: 1399,
          partUrl: 'https://amzn.to/2Tj4KAv',
          partAsin: 'asin.B07K4B9T6M',
        },
        {
          partManufacturer: 'Phanteks',
          partName: 'Enthoo Evolv X Black',
          partPrice: 212.99,
          partUrl: 'https://amzn.to/2Jpy4W8',
          partAsin: 'asin.B07GY26TZJ',
        },
        {
          partManufacturer: 'G.Skill',
          partName: 'Z RGB 32 GB DDR4 3200 (8GBx4)',
          partPrice: 362.34,
          partUrl: 'https://amzn.to/2TZdU9A',
          partAsin: 'asin.B01MSBS0UT',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Maximus XI Formula',
          partPrice: 470.99,
          partUrl: 'https://amzn.to/2Jqwfse',
          partAsin: 'asin.B07J54MQ5X',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Ryujin 360',
          partPrice: 249.99,
          partUrl: 'https://amzn.to/2WdNxKK',
          partAsin: 'asin.B07JVQXH8M',
        },
        {
          partManufacturer: 'Samsung',
          partName: '970 Evo Plus 1TB',
          partPrice: 226.18,
          partUrl: 'https://amzn.to/2Hvqnw6',
          partAsin: 'asin.B07MBQPQ62',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Thor-850P',
          partPrice: 239.99,
          partUrl: 'https://amzn.to/2HxQsub',
          partAsin: 'asin.B07HZ9JKN7',
        },
        {
          partManufacturer: 'CableMod',
          partName: 'PRO ModMesh RT-Series ASUS ROG/Seasonic',
          partPrice: 104.9,
          partUrl: 'https://amzn.to/2WisYgh',
          partAsin: 'asin.B07JL2KSGX',
        },
      ],
    },
    {
      title: 'Apex Gaming Build',
      performance: 7,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'Play like a Pro',
      image: '../images/phanteksp300tgbk.jpg',
      keyFacts:
        'A build capable of all modern titles up to WQHD-resolution and simultanous streaming.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'Phanteks',
          partName: 'Eclipse P300 Tempered Glass',
          partPrice: 62.94,
          partUrl: 'https://amzn.to/2Cgb4TO',
          partAsin: 'asin.B075DMYVBV',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT BLS2K8G4D30BESBK 16GB (8GB x2)',
          partPrice: 100.68,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },

    {
      title: 'AMD Workstation Build',
      performance: 7.5,
      bookmarked: false,
      category: 'editing',
      subtitle: 'Edit like a Pro!',
      image: '../images/fractaldesignmeshifyctg.jpg',
      keyFacts: 'Edit edit edit edit edit',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'Fractal Design',
          partName: 'Meshify C Tempered Glass',
          partPrice: 92.58,
          partUrl: 'https://amzn.to/2Tx4Edz',
          partAsin: 'asin.B079FQZM89',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT BLS2K8G4D30BESBK 16GB (8GB x2)',
          partPrice: 100.68,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },

    {
      title: 'Office PC',
      performance: 3,
      bookmarked: false,
      category: 'office',
      subtitle: 'Bargain Build',
      image: '../images/CoolerMasterMasterBoxE300L.jpg',
      keyFacts: 'Office SWAG',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Master Box E300L',
          partPrice: 34.99,
          partUrl: 'https://amzn.to/2TyB3QR',
          partAsin: 'asin.B07C2KNP2Q',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT BLS2K8G4D30BESBK 16GB (8GB x2)',
          partPrice: 100.68,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },

    {
      title: 'Lian Li Gaming Build',
      performance: 9,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'Lian Li Placeholder',
      image: '../images/lianlipco11dxbk.jpg',
      keyFacts: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'Lian Li',
          partName: 'PC-O11DX Dynamic',
          partPrice: 130.06,
          partUrl: 'https://amzn.to/2HC2mCB',
          partAsin: 'asin.B07C88X1VV',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT BLS2K8G4D30BESBK 16GB (8GB x2)',
          partPrice: 100.68,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },

    {
      title: 'Q300L Cheap Gaming',
      performance: 4.5,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'Cooler Master Placeholder',
      image: '../images/coolermasterq300l.jpg',
      keyFacts: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'MasterBox Q300L',
          partPrice: 49.93,
          partUrl: 'https://amzn.to/2Fcc9wh',
          partAsin: 'asin.B0785GRMPG',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT BLS2K8G4D30BESBK 16GB (8GB x2)',
          partPrice: 100.68,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },
    {
      title: 'NZXT Workstation Build',
      performance: 8.5,
      bookmarked: false,
      category: 'editing',
      subtitle: 'H700i Placeholder',
      image: '../images/nzxth700iw.jpg',
      keyFacts: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'NZXT',
          partName: 'H700i White',
          partPrice: 199.9,
          partUrl: 'https://amzn.to/2Te0stY',
          partAsin: 'asin.B076JG8Z6N',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT BLS2K8G4D30BESBK 16GB (8GB x2)',
          partPrice: 100.68,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },
  ]
}
