export default function PcBuildsData() {
  return [
    {
      title: 'Great Gaming',
      performance: 6,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'i5-9400F, GTX 1660Ti',
      image: '../images/fractaldesignmeshifyctgw.jpg',
      keyFacts:
        'Reasonable, cost effective gaming build for people who want to rely on Intels new entry level, budget friendly 6 core CPU, the i5-9400F and the new RTX1660Ti, a great performant GPU for high refresh rate FULL HD gaming.',
      parts: [
        {
          partManufacturer: 'Intel',
          partName: 'i5-9400F',
          partPrice: 169.0,
          partUrl: 'https://amzn.to/2Wj8iVc',
          partAsin: 'asin.B07MRCGQQ4',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce GTX1660Ti Ventus XS OC 6G',
          partPrice: 297.99,
          partUrl: 'https://amzn.to/2UdGZ1b',
          partAsin: 'asin.B07NWBSHZD',
        },
        {
          partManufacturer: 'Fractal Design',
          partName: 'Meshify C White TG',
          partPrice: 90.6,
          partUrl: 'https://amzn.to/2UfFz6g',
          partAsin: 'asin.B07B2Y9ZLM',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 16GB BLS2K8G4D30BESBK (8GB x2)',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'MSI',
          partName: 'B360-A PRO',
          partPrice: 69.0,
          partUrl: 'https://amzn.to/2UdwQ4K',
          partAsin: 'asin.B07BR3L3TT',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'CX 450 M 80 Plus Bronze',
          partPrice: 54.99,
          partUrl: 'https://amzn.to/2UdHc4t',
          partAsin: 'asin.B019NWTCEA',
        },
      ],
    },
    {
      title: 'Awesome Gaming',
      performance: 7,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'Ryzen 5 2600X, RTX 2060',
      image: '../images/phanteksp300tgbk.jpg',
      keyFacts:
        'A build capable of all modern titles up to WQHD resolution and simultanous streaming. A great choice for ambitious gamers without spending a fortune. Maybe a perfect start for your streaming career?',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600X',
          partPrice: 196.89,
          partUrl: 'https://amzn.to/2EXQxDI',
          partAsin: 'asin.B07B428V2L',
        },
        {
          partManufacturer: 'MSI',
          partName: 'GeForce RTX 2060 6GB Ventus OC',
          partPrice: 374.99,
          partUrl: 'https://amzn.to/2Tzb5gc',
          partAsin: 'asin.B07MJC8XKD',
        },
        {
          partManufacturer: 'Phanteks',
          partName: 'Eclipse P300 Tempered Glass',
          partPrice: 62.94,
          partUrl: 'https://amzn.to/2Cgb4TO',
          partAsin: 'asin.B075DMYVBV',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 16GB BLS2K8G4D30BESBK (8GB x2)',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Hyper 212 Black',
          partPrice: 34.94,
          partUrl: 'https://amzn.to/2Cg215a',
          partAsin: 'asin.B07H9HJLG5',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },
    {
      title: 'ASUS ROG Galore',
      performance: 9,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'i9-9900K, RTX2080Ti',
      image: '../images/phanteksevolvxbk.jpg',
      keyFacts:
        'If you are a fan of ASUS Republic of Gamers ecosystem, then this is the right build for you. Price-Performance ratio aside, you get all the bells and whistles and nearly unbeatable performance. 4K? VR? NP!',
      parts: [
        {
          partManufacturer: 'Intel',
          partName: 'i9-9900K',
          partPrice: 527.99,
          partUrl: 'https://amzn.to/2TmvO1X',
          partAsin: 'asin.B005404P9I',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG GEFORCE RTX2080TI STRIX',
          partPrice: 1399,
          partUrl: 'https://amzn.to/2Tj4KAv',
          partAsin: 'asin.B07K4B9T6M',
        },
        {
          partManufacturer: 'Phanteks',
          partName: 'Enthoo Evolv X Black',
          partPrice: 212.99,
          partUrl: 'https://amzn.to/2Jpy4W8',
          partAsin: 'asin.B07GY26TZJ',
        },
        {
          partManufacturer: 'G.Skill',
          partName: 'Trident Z RGB 32 GB DDR4 3200 (8GBx4)',
          partPrice: 362.34,
          partUrl: 'https://amzn.to/2TZdU9A',
          partAsin: 'asin.B01MSBS0UT',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Maximus XI Formula',
          partPrice: 470.99,
          partUrl: 'https://amzn.to/2Jqwfse',
          partAsin: 'asin.B07J54MQ5X',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Ryujin 360',
          partPrice: 249.99,
          partUrl: 'https://amzn.to/2WdNxKK',
          partAsin: 'asin.B07JVQXH8M',
        },
        {
          partManufacturer: 'Samsung',
          partName: '970 Evo Plus 1TB',
          partPrice: 226.18,
          partUrl: 'https://amzn.to/2Hvqnw6',
          partAsin: 'asin.B07MBQPQ62',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Thor-850P',
          partPrice: 239.99,
          partUrl: 'https://amzn.to/2HxQsub',
          partAsin: 'asin.B07HZ9JKN7',
        },
        {
          partManufacturer: 'CableMod',
          partName: 'PRO ModMesh RT-Series ASUS ROG/Seasonic',
          partPrice: 104.9,
          partUrl: 'https://amzn.to/2WisYgh',
          partAsin: 'asin.B07JL2KSGX',
        },
      ],
    },

    {
      title: 'Great Workstation',
      performance: 8,
      bookmarked: false,
      category: 'editing',
      subtitle: 'Ryzen 7 2700, RTX 2070',
      image: '../images/fractaldesignmeshifyctg.jpg',
      keyFacts:
        'You are content creator or need a PC for streaming? Then maybe this is the build for you. At this price point and with minimal overclocking effort the AMD Ryzen 7 2700 is the best CPU choice for decent workstations and does not have to hide.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 7 2700',
          partPrice: 219.9,
          partUrl: 'https://amzn.to/2JNjxDQ',
          partAsin: 'asin.B07B41717Z',
        },
        {
          partManufacturer: 'KFA2',
          partName: 'GeForce RTX 2070 EX 8GB',
          partPrice: 499.0,
          partUrl: 'https://amzn.to/2U0kihF',
          partAsin: 'asin.B07L2RHJS7',
        },
        {
          partManufacturer: 'Fractal Design',
          partName: 'Meshify C Tempered Glass',
          partPrice: 92.58,
          partUrl: 'https://amzn.to/2Tx4Edz',
          partAsin: 'asin.B079FQZM89',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 32GB (8GBx4) BLS4C8G4D240FSB',
          partPrice: 226.36,
          partUrl: 'https://amzn.to/2OsTyRa',
          partAsin: 'asin.B00UFBZOLE',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'B450 Pro4',
          partPrice: 82.99,
          partUrl: 'https://amzn.to/2CdKz0X',
          partAsin: 'asin.B07FVYKJHR',
        },
        {
          partManufacturer: 'be quiet!',
          partName: 'Dark Rock 4',
          partPrice: 58.85,
          partUrl: 'https://amzn.to/2Yjg0Rf',
          partAsin: 'asin.B07BYP9S95',
        },
        {
          partManufacturer: 'Samsung',
          partName: 'SSD 970 EVO Plus 500 GB M.2',
          partPrice: 123.99,
          partUrl: 'https://amzn.to/2WoMmIs',
          partAsin: 'asin.B07MFBLN7K',
        },
        {
          partManufacturer: 'WD',
          partName: 'Desktop Black 4 TB',
          partPrice: 185.99,
          partUrl: 'https://amzn.to/2TV1vo8',
          partAsin: 'asin.B0792G331G',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },

    {
      title: 'Step up your Office game',
      performance: 2,
      bookmarked: false,
      category: 'office',
      subtitle: 'Bargain Build',
      image: '../images/CoolerMasterMasterBoxE300L.jpg',
      keyFacts:
        'A fast, economical PC with Quad-Core CPU (Ryzen 3 1200), SSD storage in a lightweight 300€ package. Works well for your daily Office and/or your Multimedia needs. This build is easily upgradable, if more performance is needed.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 3 1200',
          partPrice: 72.89,
          partUrl: 'https://amzn.to/2UdCeEM',
          partAsin: 'asin.B0741DN383',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'Master Box E300L',
          partPrice: 34.99,
          partUrl: 'https://amzn.to/2TyB3QR',
          partAsin: 'asin.B07C2KNP2Q',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Vengeance LPX 8GB (2x4GB)',
          partPrice: 57.9,
          partUrl: 'https://amzn.to/2OoY3fj',
          partAsin: 'asin.B0123ZB70Q',
        },
        {
          partManufacturer: 'Gigabyte',
          partName: 'B450M S2H',
          partPrice: 65.06,
          partUrl: 'https://amzn.to/2U8DVmV',
          partAsin: 'asin.B07KX428VH',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 240GB',
          partPrice: 35.99,
          partUrl: 'https://amzn.to/2Oomqty',
          partAsin: 'asin.B01F9G43WU',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'VS350',
          partPrice: 34.99,
          partUrl: 'https://amzn.to/2U2Maly',
          partAsin: 'asin.B00LMBQD3O',
        },
      ],
    },
    {
      title: 'Excellent Gaming',
      performance: 8,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'i5-9600K, RTX2070',
      image: '../images/lianlipco11dxbk.jpg',
      keyFacts:
        'High end build in a stylish tempered glass case, capable of 4K gaming in High to Ultra settings in most modern titles combined with a lightning fast NVME SSD and fancy RGB fans.',
      parts: [
        {
          partManufacturer: 'Intel',
          partName: 'Core i5-9600K',
          partPrice: 269.9,
          partUrl: 'https://amzn.to/2WoHAdT',
          partAsin: 'asin.B07HHLX1R8',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG STRIX GEFORCE RTX2070-A8G',
          partPrice: 579.0,
          partUrl: 'https://amzn.to/2WpoZOV',
          partAsin: 'asin.B07JBGY8JC',
        },
        {
          partManufacturer: 'Lian Li',
          partName: 'PC-O11DX Dynamic',
          partPrice: 130.06,
          partUrl: 'https://amzn.to/2HC2mCB',
          partAsin: 'asin.B07C88X1VV',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Vengeance RGB PRO 16GB (2x8GB) DDR4 3200MHz',
          partPrice: 137.91,
          partUrl: 'https://amzn.to/2YoZiQc',
          partAsin: 'asin.B07D1XCKWW',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Strix Z390-E',
          partPrice: 239.0,
          partUrl: 'https://amzn.to/2Wm7IpN',
          partAsin: 'asin.B07HS7C63T',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Hydro Series H150i PRO RGB',
          partPrice: 158.99,
          partUrl: 'https://amzn.to/2WkmltG',
          partAsin: 'asin.B077FZPCRH',
        },
        {
          partManufacturer: 'Samsung',
          partName: 'SSD 970 EVO Plus 1 TB M.2',
          partPrice: 224.9,
          partUrl: 'https://amzn.to/2OpHOyJ',
          partAsin: 'asin.B07MBQPQ62',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'LL120 RGB LED PWM 3 Fan Pack',
          partPrice: 92.9,
          partUrl: 'https://amzn.to/2HDNyEt',
          partAsin: 'asin.B075VGN4M1',
        },
      ],
    },

    {
      title: 'Budget Gaming',
      performance: 4,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'Ryzen 3 1200, RX 570',
      image: '../images/coolermasterq300l.jpg',
      keyFacts:
        'A great, cost effective gaming build for fluid gaming in FULL HD resolution and even capable as an entry level VR machine. You may want to overclock the Ryzen 3 1200 slightly to unleash the full potential of this decent Quad-Core.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 3 1200',
          partPrice: 72.89,
          partUrl: 'https://amzn.to/2UdCeEM',
          partAsin: 'asin.B0741DN383',
        },
        {
          partManufacturer: 'Sapphire',
          partName: 'RADEON RX 570 4GB NITRO+',
          partPrice: 144.9,
          partUrl: 'https://amzn.to/2OsrI7f',
          partAsin: 'asin.B079FX54KZ',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'MasterBox Q300L',
          partPrice: 49.93,
          partUrl: 'https://amzn.to/2Fcc9wh',
          partAsin: 'asin.B0785GRMPG',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 16GB BLS2K8G4D30BESBK (8GB x2)',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'Gigabyte',
          partName: 'B450M S2H',
          partPrice: 65.06,
          partUrl: 'https://amzn.to/2U8DVmV',
          partAsin: 'asin.B07KX428VH',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 500 GB',
          partPrice: 55.0,
          partUrl: 'https://amzn.to/2CCdOuA',
          partAsin: 'asin.B01F9G46Q8',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'MasterWatt 450 W',
          partPrice: 49.47,
          partUrl: 'https://amzn.to/2YqVjmv',
          partAsin: 'asin.B076PBT7H6',
        },
      ],
    },
    {
      title: 'Decent Gaming PC',
      performance: 5.5,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'i5-9400F, GTX 1660',
      image: '../images/corsaircarbidespec05tg.jpg',
      keyFacts:
        'Affordable, FULL HD gaming machine. Play the newest games on high settings without hassle. It is a performant allround system and good for people who do not know where to start.',
      parts: [
        {
          partManufacturer: 'Intel',
          partName: 'i5-9400F',
          partPrice: 169.0,
          partUrl: 'https://amzn.to/2Wj8iVc',
          partAsin: 'asin.B07MRCGQQ4',
        },
        {
          partManufacturer: 'Gigabyte',
          partName: 'GeForce GTX 1660 OC 6G',
          partPrice: 239.0,
          partUrl: 'https://amzn.to/2Wrfpes',
          partAsin: 'asin.B07P76G428',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Carbide SPEC-05',
          partPrice: 58.36,
          partUrl: 'https://amzn.to/2OruZnl',
          partAsin: 'asin.B07BH23K53',
        },
        {
          partManufacturer: 'Ballistix',
          partName: 'Sport LT 16GB BLS2K8G4D30BESBK (8GB x2)',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2TBcmmL',
          partAsin: 'asin.B07HP87R9J',
        },
        {
          partManufacturer: 'MSI',
          partName: 'B360-A PRO',
          partPrice: 69.0,
          partUrl: 'https://amzn.to/2UdwQ4K',
          partAsin: 'asin.B07BR3L3TT',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 1TB',
          partPrice: 112.9,
          partUrl: 'https://amzn.to/2XWlFMB',
          partAsin: 'asin.B07D998212',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'CX 450 M 80 Plus Bronze',
          partPrice: 54.99,
          partUrl: 'https://amzn.to/2UdHc4t',
          partAsin: 'asin.B019NWTCEA',
        },
      ],
    },
    {
      title: 'Home Studio Monolith',
      performance: 9.5,
      bookmarked: false,
      category: 'editing',
      subtitle: 'i9-9900K, RTX2080Ti',
      image: '../images/coolermastersl600m.jpg',
      keyFacts:
        'A stylish PC for your studio and a beast in software like DaVinci Resolve. Less RGB, more performance. And in the mean time, you may play games in 4K or hook up a Next Gen HMD.',
      parts: [
        {
          partManufacturer: 'Intel',
          partName: 'i9-9900K',
          partPrice: 527.99,
          partUrl: 'https://amzn.to/2TmvO1X',
          partAsin: 'asin.B005404P9I',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG GEFORCE RTX2080TI STRIX',
          partPrice: 1399,
          partUrl: 'https://amzn.to/2Tj4KAv',
          partAsin: 'asin.B07K4B9T6M',
        },
        {
          partManufacturer: 'Cooler Master',
          partName: 'MasterCase SL600M',
          partPrice: 167.99,
          partUrl: 'https://amzn.to/2JAaSEV',
          partAsin: 'asin.B07JQJBV33',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Vengeance LPX 64GB 3000MHz (4x16GB)',
          partPrice: 432.83,
          partUrl: 'https://amzn.to/2UUcudK',
          partAsin: 'asin.B01HFR9BY6',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'WS Z390 Pro',
          partPrice: 421.84,
          partUrl: 'https://amzn.to/2UV7UvW',
          partAsin: 'asin.B07JMB6CNL',
        },
        {
          partManufacturer: 'be quiet!',
          partName: '360mm Silent LOOP',
          partPrice: 144.94,
          partUrl: 'https://amzn.to/2WmcaEV',
          partAsin: 'asin.B0721STR79',
        },
        {
          partManufacturer: 'Samsung',
          partName: '970 Evo Plus 1TB',
          partPrice: 226.18,
          partUrl: 'https://amzn.to/2Hvqnw6',
          partAsin: 'asin.B07MBQPQ62',
        },
        {
          partManufacturer: 'WD',
          partName: 'Desktop Black 4 TB',
          partPrice: 185.99,
          partUrl: 'https://amzn.to/2TV1vo8',
          partAsin: 'asin.B0792G331G',
        },
        {
          partManufacturer: 'Seasonic',
          partName: 'Focus Plus 750W Gold 80 Plus',
          partPrice: 106.83,
          partUrl: 'https://amzn.to/2WmViOv',
          partAsin: 'asin.B073GWKDVM',
        },
      ],
    },
    {
      title: 'Threadripper Workstation',
      performance: 10,
      bookmarked: false,
      category: 'editing',
      subtitle: '2920WX, RTX2080Ti',
      image: '../images/fractaldesigndefines2.jpg',
      keyFacts:
        'Relyable, massive 12-core workstation for your heavy workloads without frills. It satisfies all your needs regarding power, storage and speed.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen Threadripper 2920WX',
          partPrice: 653.95,
          partUrl: 'https://amzn.to/2WsvYXr',
          partAsin: 'asin.B07JDF4QP2',
        },
        {
          partManufacturer: 'KFA2',
          partName: 'GeForce RTX 2080 Ti OC Black',
          partPrice: 1099.0,
          partUrl: 'https://amzn.to/2WqwR2I',
          partAsin: 'asin.B07MTNMBFH',
        },
        {
          partManufacturer: 'Fractal Design',
          partName: 'Define S2 Blackout',
          partPrice: 150.89,
          partUrl: 'https://amzn.to/2JC0U64',
          partAsin: 'asin.B07J1RMZB9',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Vengeance LPX 64GB 3000MHz (4x16GB)',
          partPrice: 432.83,
          partUrl: 'https://amzn.to/2UUcudK',
          partAsin: 'asin.B01HFR9BY6',
        },
        {
          partManufacturer: 'ASRock',
          partName: 'X399 Phantom Gaming 6',
          partPrice: 279.66,
          partUrl: 'https://amzn.to/2TzNvLd',
          partAsin: 'asin.B07L5TP1SJ',
        },
        {
          partManufacturer: 'be quiet!',
          partName: 'Dark Rock Pro TR4',
          partPrice: 76.85,
          partUrl: 'https://amzn.to/2HHjQi0',
          partAsin: 'asin.B07J589GHF',
        },
        {
          partManufacturer: 'Samsung',
          partName: '970 Evo Plus 1TB',
          partPrice: 226.18,
          partUrl: 'https://amzn.to/2Hvqnw6',
          partAsin: 'asin.B07MBQPQ62',
        },
        {
          partManufacturer: 'WD',
          partName: 'Desktop Black 6 TB',
          partPrice: 229.0,
          partUrl: 'https://amzn.to/2JDTX4l',
          partAsin: 'asin.B0792GSD6N',
        },
        {
          partManufacturer: 'be quiet!',
          partName: 'Straight Power 11 750W',
          partPrice: 115.99,
          partUrl: 'https://amzn.to/2TA1gtx',
          partAsin: 'asin.B078X1KZ8N',
        },
      ],
    },
    {
      title: 'White VR Mini PC',
      performance: 7.5,
      bookmarked: false,
      category: 'gaming',
      subtitle: 'Ryzen 5 2600, RTX 2070',
      image: '../images/nzxth200bw.jpg',
      keyFacts:
        'A high end build in a magnificent, sleek looking white case, well suited placing it next to your Home Entertainment system or on top of your desk in a white themed setup. High refresh rate, high resolution, VR? No problem.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 5 2600',
          partPrice: 162.99,
          partUrl: 'https://amzn.to/2UfKTqc',
          partAsin: 'asin.B07B41WS48',
        },
        {
          partManufacturer: 'Gigabyte',
          partName: 'GeForce RTX 2070 Gaming OC White 8G',
          partPrice: 569.0,
          partUrl: 'https://amzn.to/2CFBHS3',
          partAsin: 'asin.B07JJ7YKJZ',
        },
        {
          partManufacturer: 'NZXT',
          partName: 'H200B-W',
          partPrice: 89.9,
          partUrl: 'https://amzn.to/2U5XAUO',
          partAsin: 'asin.B07D7M8XR9',
        },
        {
          partManufacturer: 'Patriot',
          partName: '16GB Viper RGB DDR4-3200 Kit White PVR416G320C6KW ',
          partPrice: 144.99,
          partUrl: 'https://amzn.to/2TZj1aw',
          partAsin: 'asin.B07CX53TKZ',
        },
        {
          partManufacturer: 'ASUS',
          partName: 'ROG Strix B450-I',
          partPrice: 150.99,
          partUrl: 'https://amzn.to/2OoFFmZ',
          partAsin: 'asin.B07F6ZP4RW',
        },
        {
          partManufacturer: 'NZXT',
          partName: 'X52 All-in-One Cooler',
          partPrice: 146.58,
          partUrl: 'https://amzn.to/2CGhCLE',
          partAsin: 'asin.B06XYSVXYX',
        },
        {
          partManufacturer: 'WD',
          partName: 'Blue 1 TB SATA M.2 SSD',
          partPrice: 125.02,
          partUrl: 'https://amzn.to/2U0JxR9',
          partAsin: 'asin.B073SB2MXT',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'TXM Gold 550W 80+ Gold',
          partPrice: 77.99,
          partUrl: 'https://amzn.to/2O1rxjf',
          partAsin: 'asin.B06WV7Z1ZW',
        },
      ],
    },
    {
      title: 'Budget Office/Multimedia',
      performance: 2.5,
      bookmarked: false,
      category: 'office',
      subtitle: 'Cost effective daily driver',
      image: '../images/sharkoonsharkzonec10.jpg',
      keyFacts:
        'Mini PC with a great price-performance ratio. With its integrated Vega 8 GPU, the Ryzen 3 2200G CPU is a great overall performer for all your daily tasks, from photo editing to light gaming. All components were chosen with an easy, cost effective upgrade path in mind.',
      parts: [
        {
          partManufacturer: 'AMD',
          partName: 'Ryzen 3 2200G',
          partPrice: 93.9,
          partUrl: 'https://amzn.to/2Tzntb9',
          partAsin: 'asin.B079D3DBNM',
        },
        {
          partManufacturer: 'Sharkoon',
          partName: 'Shark Zone C10 ITX',
          partPrice: 39.99,
          partUrl: 'https://amzn.to/2Tw6u9L',
          partAsin: 'asin.B00TJBCASG',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'Vengeance LPX 8GB DDR4 3000MHz',
          partPrice: 46.49,
          partUrl: 'https://amzn.to/2Ot7ESe',
          partAsin: 'asin.B07B4FRMGV',
        },
        {
          partManufacturer: 'Gigabyte',
          partName: 'Aorus Pro AMD B450 ITX',
          partPrice: 120.99,
          partUrl: 'https://amzn.to/2Ua9cpB',
          partAsin: 'asin.B07GZW32BV',
        },
        {
          partManufacturer: 'SanDisk',
          partName: 'SSD PLUS 480GB',
          partPrice: 55.0,
          partUrl: 'https://amzn.to/2JCxcNZ',
          partAsin: 'asin.B01F9G46Q8',
        },
        {
          partManufacturer: 'Corsair',
          partName: 'VS350',
          partPrice: 34.99,
          partUrl: 'https://amzn.to/2U2Maly',
          partAsin: 'asin.B00LMBQD3O',
        },
      ],
    },
  ]
}
